def datacfg():
    datacfg = dict()
    datacfg["abalone"] = dict()
    datacfg["abalone"]["filepath"] = "./data/abalone.pkl"
    datacfg["abalone"]["targets"] = ["rings"]
    datacfg["abalone"]["probtype"] = ["regression", "classification"]
    datacfg["autoMpg"] = dict()
    datacfg["autoMpg"]["filepath"] = "./data/autoMpg.pkl"
    datacfg["autoMpg"]["targets"] = ["mpg"]
    datacfg["autoMpg"]["probtype"] = ["regression"]
    datacfg["bankMarketing"] = dict()
    datacfg["bankMarketing"]["filepath"] = "./data/bankMarketing.pkl"
    datacfg["bankMarketing"]["targets"] = ["y"]
    datacfg["bankMarketing"]["probtype"] = ["classification"]
    datacfg["bostonHousing"] = dict()
    datacfg["bostonHousing"]["filepath"] = "./data/bostonHousing.pkl"
    datacfg["bostonHousing"]["targets"] = ["MEDV"]
    datacfg["bostonHousing"]["probtype"] = ["regression"]
    datacfg["heartDiseaseWisconsin"] = dict()
    datacfg["heartDiseaseWisconsin"]["filepath"] = "./data/heartDiseaseWisconsin.pkl"
    datacfg["heartDiseaseWisconsin"]["targets"] = ["num"]
    datacfg["heartDiseaseWisconsin"]["probtype"] = ["regression"]
    datacfg["wineCultivar"] = dict()
    datacfg["wineCultivar"]["filepath"] = "./data/wineCultivar.pkl"
    datacfg["wineCultivar"]["targets"] = ["cultivar"]
    datacfg["wineCultivar"]["probtype"] = ["classification"]
    datacfg["winequality-red"] = dict()
    datacfg["winequality-red"]["filepath"] = "./data/winequality-red.pkl"
    datacfg["winequality-red"]["targets"] = ["quality"]
    datacfg["winequality-red"]["probtype"] = ["regression", "classification"]
    datacfg["winequality-white"] = dict()
    datacfg["winequality-white"]["filepath"] = "./data/winequality-white.pkl"
    datacfg["winequality-white"]["targets"] = ["quality"]
    datacfg["winequality-white"]["probtype"] = ["regression", "classification"]
    datacfg["iris"] = dict()
    datacfg["iris"]["filepath"] = "./data/iris.pkl"
    datacfg["iris"]["targets"] = ["class"]
    datacfg["iris"]["probtype"] = ["classification"]
    datacfg["pima"] = dict()
    datacfg["pima"]["filepath"] = "./data/pima.pkl"
    datacfg["pima"]["targets"] = ["class"]
    datacfg["pima"]["probtype"] = ["classification"]
    datacfg["adult"] = dict()
    datacfg["adult"]["filepath"] = "./data/adult.pkl"
    datacfg["adult"]["targets"] = ["class"]
    datacfg["adult"]["probtype"] = ["classification"]
    return datacfg
